export default function AdminDashboard() {
  return (
      <div className="p-6">
            <div className="mb-6">
                    <h1 className="text-xl font-medium text-gray-900">Tableau de bord</h1>
                            <p className="text-sm text-gray-500">Turquoise Voyage — Gestion des dossiers visa</p>
                                  </div>
                                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                                                {[
                                                          ['Dossiers actifs','24','text-blue-600'],
                                                                    ['RDV cette semaine','7','text-amber-600'],
                                                                              ['Accordés ce mois','18','text-green-600'],
                                                                                        ['Taux accord','90%','text-teal-600']
                                                                                                ].map(([l,v,c]) => (
                                                                                                          <div key={l} className="bg-white border border-gray-200 rounded-xl p-4">
                                                                                                                      <p className="text-xs text-gray-500 mb-1">{l}</p>
                                                                                                                                  <p className={`text-2xl font-medium ${c}`}>{v}</p>
                                                                                                                                            </div>
                                                                                                                                                    ))}
                                                                                                                                                          </div>
                                                                                                                                                                <div className="bg-white border border-gray-200 rounded-xl p-5">
                                                                                                                                                                        <p className="text-sm font-medium mb-4">Dossiers récents</p>
                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                          {[
                                                                                                                                                                                                      ['Karim Belhaj','🇫🇷 France · Touristique','RDV pris','bg-amber-50 text-amber-700'],
                                                                                                                                                                                                                  ['Leila Gharbi','🇫🇷 France · Étudiant','En cours','bg-blue-50 text-blue-700'],
                                                                                                                                                                                                                              ['Ahmed Triki','🇮🇹 Italie · Touristique','Accordé','bg-green-50 text-green-700']
                                                                                                                                                                                                                                        ].map(([nom,dest,statut,sc]) => (
                                                                                                                                                                                                                                                    <div key={nom} className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0">
                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                  <p className="text-sm font-medium text-gray-900">{nom}</p>
                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-500">{dest}</p>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                              <span className={`text-xs px-2.5 py-1 rounded-full font-medium ${sc}`}>{statut}</span>
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                        }
